"""Initial migration2.

Revision ID: ab6eb789a983
Revises: 
Create Date: 2023-12-24 17:59:18.048099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6eb789a983'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hint', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('rotation', sa.String(length=10), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
