"""changed length correctly

Revision ID: db8fdc76e312
Revises: ab6eb789a983
Create Date: 2023-12-24 18:03:17.926081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db8fdc76e312'
down_revision = 'ab6eb789a983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('hint',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('hint',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
